spring:
  profiles:
    active: dev
  application:
    name: messaging_api
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  level:
    org:
      springframework:
        cache: TRACE

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
    operations-sorter: "method"
  packagesToScan: com.br.messaging_api.application.controller

server:
  port: 8082
  shutdown: graceful
